### ISSUE TITLE
MPU-6050 not working

### ISSUE THREAD

**Issue by devdrik** [devdrik/hackmelamp#1]
The MPU-6050 IC is not working properly. I can actually sometimes establish a connection to it using the [MPU6050 lib by jrowberg](https://github.com/jrowberg/i2cdevlib/tree/master/Arduino/MPU6050). But I only receive 0's. Most of the time the connection just fails.
If you can spot any errors on the board, please let me know.

**Comment by 1randy** [comment]
according to the schematics, R13/R14 (i2c pullups) are 10k; in 3V3 systems, those should be 4k7 or even lower (3k3/2k7).
that could explain the connection issues.

**Comment by devdrik** [comment]
Thanks. I swapped them, but it did not fix it.

The problem was that I got a bad batch of MPU6050 ICs. I tested 7 of them on 3 different PCBs. None of them worked. Then I tried one from a different batch and it worked immediately...
